backend:
  name: github
  repo: K-Usman/usmankamran.github.io
  branch: master
  open_authoring: false

# Local backend for development
local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "public/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - {label: "Title", name: "title", type: "string"}
      - {label: "Publish Date", name: "date", type: "datetime"}
      - {label: "Description", name: "description", type: "string"}
      - {label: "Body (Markdown)", name: "body", type: "markdown"}
